### ISSUE TITLE
If there are several sessions, it does not calculate the balance correctly and the balance is not added when you win

### ISSUE THREAD

**Issue by Inquisitor007** [vanhbakaa/Coinsweeper#10]
If there are several sessions, it does not calculate the balance correctly and the balance is not added when you win

 | INFO     | 437 - MAIN |  Won game : 86f38310-38e1-47d1-ace1-d9234947ccd7 | Earned 320
 | INFO     | 229 - MAIN | Balance: 1820
 
 The balance was 25600 and remains 25600

**Comment by vanhbakaa** [comment]
I fixed you can run and disable multi thread and i will work fine

**Comment by jason866695** [comment]
> I fixed you can run and disable multi thread and i will work fine

i have another account,and i save another file called coinsweeper2,and make sure i run the code in single thread,the second command window looks normal,but if i check my telegram app,my score did not increase.Did i do something wrong?

**Comment by vanhbakaa** [comment]
They got ratelimited so u need proxy if u want to run 2 or more account at the same time
