### ISSUE TITLE
Max retries exceed

### ISSUE THREAD

**Issue by thapld** [vanhbakaa/Coinsweeper#24]
![image](https://github.com/user-attachments/assets/2827ae10-9c87-4c55-b4ac-5d2020e3ffa6)

Please fix it

**Comment by vanhbakaa** [comment]
U have to install a new ssl cert for your pc

**Comment by thapld** [comment]
Thank you. Let my try

---
Sent with Gmail for Sidekick Browser <https://join.meetsidekick.com/_7ww23>
