### ISSUE TITLE
refresh token failed

### ISSUE THREAD

**Issue by 0xTaaa** [vanhbakaa/Coinsweeper#25]
“refreshToken must be a jwt string”

**Comment by breelock** [comment]
You have been banned in bybit coinsweeper. I have the same situation

**Comment by Insomnia731** [comment]
> You have been banned in bybit coinsweeper. I have the same situation

Banned from start? I launched it for the first time and the same message.

**Comment by breelock** [comment]
No, I used this program and I was banned after a week. There is a wave of bans now, even honest players suffer.

**Comment by TemoSulava** [comment]
yep that's a ban

**Comment by xcybermanx** [comment]
![saper](https://github.com/user-attachments/assets/045c1efa-c679-469b-9549-62fce94a8718)
![rgrgrgr](https://github.com/user-attachments/assets/f109aae6-f082-4f1a-bd42-01244fc7879b)
Banned :(

**Comment by thapld** [comment]
Have a fix?

**Comment by breelock** [comment]
If you are banned, you need to create a new telegram account. Then download the update of this repository and it will work
