### ISSUE TITLE
Re-Login Error

### ISSUE THREAD

**Issue by udaydeep1992** [vanhbakaa/Coinsweeper#4]
![image](https://github.com/user-attachments/assets/49deb9d9-119c-4cb6-9eaa-22f104d6973f)

**Comment by JustPandaEver** [comment]
https://github.com/winsnip/BybitCoinsweeper

Use query

**Comment by Inquisitor007** [comment]
After sleep ... 
Unknown error: Object of type set is not JSON serializable

**Comment by vanhbakaa** [comment]
fixed
