### ISSUE TITLE
After sleep it's not work I have to restart the bot than work again

### ISSUE THREAD

**Issue by Rayhan4430** [vanhbakaa/Coinsweeper#7]
![Screenshot_20240929-141925](https://github.com/user-attachments/assets/d6c020d2-b1c3-4623-9796-b385d117e102)

After completing three game it goes for sleep which is great but after the sleeping time it not works. 

Error come " Unknown error: Object of type set is not JSON serializable "

Then I start the bot again then it works again and stop working with this error after sleep

**Comment by vanhbakaa** [comment]
Try newest version
